### ISSUE TITLE
Dtype checks should use dtype.kind instead of ==

### ISSUE THREAD

**Issue by Erotemic** [flrs/blend_modes#1]
In at least one place this package checks that 

```python
assert img_in.dtype == np.float,
```
On some platforms this forces images to be of dtype `np.float32` and on others they must be `np.float64` because `np.float` is just an alias for the native floating type on the system. This library should assert floating type input, but it should not care if it is a 32 or 64 bit float. 

The fix is to replace all code of the previous style with: 

```python
assert img_in.dtype.kind == 'f'
```

with will work with both float32 and float64 types.

**Comment by flrs** [comment]
Hi @Erotemic, thanks for the suggestion! I just fixed this.
