### ISSUE TITLE
'Subtract' Blend Does Not Work

### ISSUE THREAD

**Issue by malemo** [flrs/blend_modes#19]
For some reason Subtract blend mode does not work for me. The result is black or white image. 
The blending code looks correct: 
>comp = img_layer_norm[:, :, :3] - img_in[:, :, :3]
    ratio_rs = np.reshape(np.repeat(ratio, 3), [comp.shape[0], comp.shape[1], comp.shape[2]])
    img_out = np.clip(comp * ratio_rs + img_in_norm[:, :, :3] * (1.0 - ratio_rs), 0.0, 1.0)
    img_out = np.nan_to_num(np.dstack((img_out, img_in_norm[:, :, 3]))) 

All other modes work fine. 
What could be the issue?

**Comment by m4nuC** [comment]
I am experiencing the same issue, how did you get around it ?

**Comment by Black-Platypus** [comment]
Same/similar issue here.
It's not always completely white: In this test, I used `subtract(b, a, 0.65)` and you can still see some outlines of the stones.
Compare against Photoshop's subtraction in "ps_sub.png"

<img width="1064" height="332" alt="Image" src="https://github.com/user-attachments/assets/8a2d31ee-4e1f-4aec-b965-74ffd27546cc" />

<img width="512" height="768" alt="Image" src="https://github.com/user-attachments/assets/c21bb3f7-ba5b-4360-ab84-92d9dcca06d1" />
<img width="512" height="768" alt="Image" src="https://github.com/user-attachments/assets/44575d22-725c-4edc-84b4-cd672d34f362" />
<img width="512" height="768" alt="Image" src="https://github.com/user-attachments/assets/860727b1-3688-411c-a592-e5656fee7da5" />
<img width="512" height="768" alt="Image" src="https://github.com/user-attachments/assets/7a083a72-20f2-4774-8a9d-bd3eae8acd3c" />

(This is an approximation to the best of my abilities; my python script does some resizing and cropping beforehand, which I re-did in Photoshop just to illustrate an example; the random opacity chosen was ~0.59027965530238)
