### ISSUE TITLE
How to combine mutiple blend_modes toghether?

### ISSUE THREAD

**Issue by TejasBob** [flrs/blend_modes#2]
For example,
Overlay blend mode is combination of multiply and screen.
Overlay mode is not present in blend_modes.
How can I combine existing multiply and screen modes to perform overlay blending?

Tejas

**Comment by flrs** [comment]
Hi @TejasBob, thank you for your pull request #3! I think this issue is now resolved, do you agree?

**Comment by TejasBob** [comment]
Yes!
