### ISSUE TITLE
Question adding Color Luminosity Hue and Saturation?

### ISSUE THREAD

**Issue by FredHappyface** [flrs/blend_modes#20]
Hello

Would it be possible to add the following from the ora spec to this project?

I would be very happy to submit a pr if this is something that you would be interested in

ora | blend 
-- | -- |
svg:color | Color 
svg:luminosity | Luminosity
svg:hue | Hue 
svg:saturation | Saturation

Thank you for your time 
FH

**Comment by Black-Platypus** [comment]
I don't see the four new blend modes, but this was closed as "completed".
Was this ever implemented?
