### ISSUE TITLE
Can't install blend_modes

### ISSUE THREAD

**Issue by devBram97** [flrs/blend_modes#21]
Every time I try to install I get the following error:

ERROR: Command errored out with exit status 1:
     command: 'c:\users\bram\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Bram\\AppData\\Local\\Temp\\pip-install-hpxlb90y\\blend-modes_74cbb38837e54b33ad88842e7ef2ea0c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Bram\\AppData\\Local\\Temp\\pip-install-hpxlb90y\\blend-modes_74cbb38837e54b33ad88842e7ef2ea0c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Bram\AppData\Local\Temp\pip-pip-egg-info-v3d_bvhx'
         cwd: C:\Users\Bram\AppData\Local\Temp\pip-install-hpxlb90y\blend-modes_74cbb38837e54b33ad88842e7ef2ea0c\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\bram\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "c:\users\bram\appdata\local\programs\python\python38\lib\site-packages\setuptools\extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "c:\users\bram\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 16, in <module>
        import pkg_resources
      File "c:\users\bram\appdata\local\programs\python\python38\lib\site-packages\pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Anyone who can help?

**Comment by flrs** [comment]
Hi @devBram97,

I suspect that this is not necessarily an issue with blend_modes. A quick google search revealed this [Stackoverflow post](https://stackoverflow.com/questions/44761958/using-pip3-module-importlib-bootstrap-has-no-attribute-sourcefileloader). Are you trying to install blend_modes via pip?

**Comment by flrs** [comment]
Since there has not been any response, I am closing this issue.
