### ISSUE TITLE
np.NAN error

### ISSUE THREAD

**Issue by yuxi-liu-wired** [flrs/blend_modes#29]
<https://github.com/flrs/blend_modes/blob/master/blend_modes/blending_functions.py#L69>

should be changed to 

```python
    ratio[ratio == np.nan] = 0.0
```

**Comment by flrs** [comment]
Dear @yuxi-liu-wired , thank you for your kind bug report. As I do not have resources to fix this right now, I would kindly invite you to do a pull request with the change, if you are interested. Thanks a lot!

**Comment by Mahfoudh94** [comment]
It is funny that I found the library moments ago and found this bug, came to report it just to find it the latest reported issue.

**Comment by flrs** [comment]
Sorry for this experience, I do not have the resources right now to maintain this library. If there is anything I can do to make it easier for you to help fixing the issue, please let me know. I am happy to accept a PR.

**Comment by Mahfoudh94** [comment]
@flrs is there a way to rerun the CI pipeline for this commit?

**Comment by Mahfoudh94** [comment]
@flrs @yuxi-liu-wired I think we can say "Congrats" as this issue is seemingly resolved, tested it and it works.

**Comment by flrs** [comment]
I agree, glad we got it fixed and thank you all for your help! 🙌
