### ISSUE TITLE
Applying BlendModes to JPGS

### ISSUE THREAD

**Issue by cmooreml** [flrs/blend_modes#5]
Does anyone know how to apply blendmode to an JPG? I tried converting to ... but no luck.

```
rgba = cv2.cvtColor(img, cv2.COLOR_RGB2RGBA)
```

**Comment by mabdullahrafique** [comment]
Same.

**Comment by mabdullahrafique** [comment]
I got it work.
Load image from PIL.
img = Image.open('xyz.jpg')
img  = img.convert('RGBA')
img = numpy.array(img)  # Inputs to blend_modes need to be numpy arrays.
img = img.astype(float)  .
It will work.
**So, convert to RGBA when it is PIL image will work**

**Comment by flrs** [comment]
Closing this since it looks like we have a solution! Thanks, @mabdullahrafique for following up on this!
