### ISSUE TITLE
API feedback

### ISSUE THREAD

**Issue by SaschaSchlemmer** [flrs/blend_modes#7]
During experimenting with `blend_modes` two things struck me as odd:

- module import is weird in that the actual functions don't live on the top level of the module i.e. 

      from blend_modes import soft_light # or
      import blend_mode 

  would be much nicer.

- I was really surprised that `blend_modes` functions mutate their inputs

**Comment by flrs** [comment]
Thanks for your feedback. I agree on all points. This should be fixed in a future release.

**Comment by flrs** [comment]
Resolved in version 2.0.1.

**Comment by flrs** [comment]
I am reopening this because the modification of inputs is a bug, and would not be expected by the user.
